apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::270247528755:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::270247528755:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-62KIAHOFLGRC
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-31T13:36:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1926"
  uid: 5bdd64a0-29d2-4b17-92fb-280f3ae020d1